[config]
feed_username = phukijnat.mek@gmail.com
feed_password = N@n085463192

[confluent_config]
confluent_bootstrap_servers = YOUR_CONFLUENT_BOOTSTRAP_SERVERS
confluent_key = YOUR_CONFLUENT_KEY
confluent_secret = YOUR_CONFLUENT_SECRET
